### PR TITLE
Integrate "VideoBackends: Query fixes and cleanups" by K0bin

### PR DESCRIPTION
**Pull request by Medard22**
https://github.com/dolphin-emu/dolphin/pull/11286

### CODE REVIEW

**Comment by Medard22** [comment]
I am not merging this now. On my test device with SD855+ this causes graphic glitches and a hard freeze in Super Mario Sunshine on the Vulkan backend. It will need some investigation.

**Comment by ivan89el** [comment]
The new version crashes when trying to load custom textures

**Comment by Medard22** [comment]
Thanks for the report, this is a feature I don´t use at all. I need more information though. What is your hardware, what game did you test it on, and if the custom textures work okay in the latest stable?
Could you test it with this version and report back? - https://drive.google.com/file/d/127CmlynmaOJ8CZD-G17Qz5-g5aRTbyQL/view?usp=sharing
This build contains all merged fixes except those from this PR. Thanks.

**Comment by ivan89el** [comment]
@Medard22 Unfortunately, this doesn't work either. v2.1.010 Latest on May 4 freezes too.
Anbernic rg405m device, unisoc t618

**Comment by Medard22** [comment]
Ok, so this issue is not related to this PR. I've set up discussions now. Let's continue discussing it [in this thread ](https://github.com/Medard22/Dolphin-MMJR2-VBI/discussions/33). I need further information.

- Game and version (PAL/NTSC)
- Which texture pack - (send me a link, so I can test it myself)

**Comment by Medard22** [comment]
So I got some extra feedback that successfully tested this PR on SD 8 Gen 1 and Dimensity 1200. As this really looks as a driver bug specific to my device I am merging this PR. If problems emerge after public release it can be always reverted. For now I would rather uphold code parity to Dolphin Official.

**Pull request merged**
